### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
Following your request in the tweet:
https://twitter.com/SumonMSelim/status/1179593511374639109

Here it is your brand new logo. Hope you like it!

image

### CODE REVIEW

**Comment by SumonMSelim** [comment]
@caneco thanks a lot! I would love to get the HD version file of the logo and icon :)

**Comment by caneco** [comment]
@SumonMSelim here you have a BIG version… more stuff ping me next month, if you don't mind 😄 

[laravel-backbone-BIG.png.zip](https://github.com/Laravel-Backbone/laravel-backbone/files/3694049/laravel-backbone-BIG.png.zip)

**Comment by SumonMSelim** [comment]
@caneco Thanks. I am coming to Lisbon next month to attend the Web Summit. Would love to have a cup of coffee with you!

**Comment by caneco** [comment]
@SumonMSelim nice!!! I'm going to be there as well. We really need to that 🔥

**Pull request merged**
